### ISSUE TITLE
Create wiki home page

### ISSUE THREAD

**Issue by Knayam7** [NRG948/NRGRobot2017#22]
Go to the wiki tab and edit the home page

Add leadership names, robot challenge, info about our team and what you think is necessary.
Before you save it, have someone from Leadership look it over

**Comment by gregoryquick** [comment]
Two things relevant to this- the [nrg website](http://nrg948.com/) has the information you mentioned there and we also have a [wiki](http://wiki.nrg948.com/public/) for the club,rather than for this one repository, which would be better suited to have this information, however I do not believe that the password has been sent in any just club-wide notifications.
